backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

collections:
  - name: "" # Used in routes, e.g., /admin/collections/blog
    label: "" # Used in the UI
    folder: "content/{{slug}}" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "index" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Body", name: "body", widget: "markdown"}